config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flat)
    @flat.save
  end

  private

  def params_flat
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
<h1>All our Flats (<%= @flats.count %>)</h1>
<div class="cards">
<% @flats.each do |flat| %>
  <div class="card">
    <ul class="list">
      <li> <h2><%= flat.name %></h2></li>
      <li> <p><%= flat.address %></p></li>
      <li> <i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>   <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></li>
    </ul>
    <div class="info">
      <%= link_to "More info", flat_path(flat) %>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :price_per_night %>
<%= f.input :number_of_guests %>
<%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="card">
  <h1><%= @flat.name %></h1>
  <p>Address: <%= @flat.address %></p>
</div>
<div class="card">
  <h2>A bit more about this flat</h2>
  <p><%= @flat.description %></p>
</div>
<div class="card">
  <h2>Details</h2>
<p><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %>   <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %></p>
</div>
<p><%= link_to "Back to all flats", flats_path %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <div class="banner">
      <h3>Simple Airbnb</h3>
      <%= link_to "Add a flat", new_flat_path %>
    </div>
    <%= yield %>
  </body>
</html>